### ISSUE TITLE
🐛 - postinstall and unistall messages does't showing.

### ISSUE THREAD

**Issue by HenrikSantos** [HenrikSantos/rc-commands#10]
Idk why :(

**Comment by israelss** [comment]
This is not a bug.

The postinstall script will run but will not print anything to the console.
See https://github.com/npm/cli/issues/3647

And the postuninstall script will never run.
See https://docs.npmjs.com/cli/v9/using-npm/scripts#a-note-on-a-lack-of-npm-uninstall-scripts

**Comment by hbaldwinRPT** [comment]
> This is not a bug.
> 
> The postinstall script will run but will not print anything to the console. See [npm/cli#3647](https://github.com/npm/cli/issues/3647)
> 
> And the postuninstall script will never run. See https://docs.npmjs.com/cli/v9/using-npm/scripts#a-note-on-a-lack-of-npm-uninstall-scripts
nope, it doesnt. you can tell because when you look to see the other things the script does that doesnt happen either. i have been having the same issue to no avail. the script isnt running and nothing i have tried has getten prepare, or postinstall to fire at all.
