### ISSUE TITLE
✨ Add option to include props to component

### ISSUE THREAD

**Issue by israelss** [HenrikSantos/rc-commands#13]
How to do this?
I mean, what format would be accepted?
A comma separated string?
An array?
Which formats are possible/accepted by commander?

Also, we must take into account the prop types when generating TS components.

**Comment by HenrikSantos** [comment]
I think something like "rc c example --str prop1,prop2 --int prop3,prop4 --bool prop5,prop6" looks good, then you can create the array with split.

Putting the PropTypes in js and creating an interface or type aliases in TS would be nice too.

A cool extra would be to be able to pass a useState function something like "rc c example --use-state fn01=number,fn02=string,fn03=bool" then you could split with comma and then with equals operator, and it would output this:

interface IExample {
  fn01: Dispatch<SetStateAction<number>>;
  fn02: Dispatch<SetStateAction<string>>;
  fn03: Dispatch<SetStateAction<boolean>>;
}

obviously this would only be a option for TS.

**Comment by israelss** [comment]
I've just read about [variadic option](https://github.com/tj/commander.js#variadic-option) on commander docs, and it seems the best option, but I propose a solution a little bit different of yours.

Example 1: Specifying simple/primitive props (with destructuring)
```sh
rc c example --props prop1:string prop2:number prop3:boolean prop4 --destructureProps
```
would generate something like:

```tsx
type ExampleProps = {
  prop1: string;
  prop2: number;
  prop3: boolean;
  prop4: unknown;
}

export function Example({ prop1, prop2, prop3, prop4 }: ExampleProps) {
  ...
}
```

Example 2: Specifying simple/primitive props and setState props (without destructuring)
```sh
rc c example --props prop1:string func1:setState(Record<string, number>) func2:setState(boolean) func3:setState
```
would generate something like:

```tsx
type ExampleProps = {
  prop1: string;
  func1: Dispatch<SetStateAction<Record<string, number>>>;
  func2: Dispatch<SetStateAction<boolean>>;
  func3: Dispatch<SetStateAction<unknown>>;
}

export function Example(props: ExampleProps) {
  const { prop1, func1, func2, func3 } = props;
  ...
}
```

Example 3: Specifying props and states
```sh
rc c example --props prop1:string func1:setState(boolean) --state state1:boolean[false] state2:string state3:Record<string, string> state4 --destructureProps
```
would generate something like:

```tsx
type ExampleProps = {
  prop1: string;
  func1: Dispatch<SetStateAction<boolean>>;
}

export function Example({ prop1, func1 }: ExampleProps) {
  const [state1, setState1] = useState<boolean>(false);
  const [state2, setState2] = useState<string>();
  const [state3, setState3] = useState<Record<string, string>>();
  const [state4, setState4] = useState<unknown>();
  ...
}
```

What do you think?

**Comment by HenrikSantos** [comment]
I didn't like it for primitives values, because it will be too verbose and repetitive, so, I don't see why someone would use it. I think the main objective of the CLI is to be fast and productive, in this way, it's faster to just type in the file. But I think it's good for the useState and other functions.

Taking this into consideration, for primitive types, I think the best would be: 

"rc c example -s prop1,prop2 -i prop3,prop4 -b prop5,prop6" // with alias --string, --integer, --boolean

If you want, I can do a vote on Linkedin, to see what people prefer.

I liked the destructuring flag.

**Comment by israelss** [comment]
I like the ideia of aliases. But how do we do with optional values?

Option 1 (`<>` indicates optional):
```sh
rc c example -s prop1 <prop2>
```

Option 2 (`?` indicates optional):
```sh
rc c example -s prop1 prop2?
```

Other alternatives???

I think it is a good ideia to gather people opinion with a voting :+1:

That said, I don't think we should support *all* primitive types... i mean `bigint`, `null`, `symbol` and `undefined` seems too much effort for too little benefit, like you pointed out, it's often faster to just type in file.

But for `boolean`, `number` and `string` we could definitelly use aliases (-b, -n, -s)

**Comment by HenrikSantos** [comment]
I prefer option 2, sems easyer to understand and more intuitive.

**Comment by israelss** [comment]
I'm starting to work on this :handshake:

**Comment by israelss** [comment]
We may have a problem here. I use zsh as my default shell, and when testing the optional props, I get a `zsh: no matches found:` error, because I'm using `?` as the optional marker, and zsh interprets it as a wildcard.
With bash this isn't a problem.

As far as I see we can:

- Change the optional marker to something else, that doesn't get interpreted as a wildcard
- Instruct the users to create an alias for rc when using zsh (alias rc="noglob rc")

What do you think @HenrikSantos?

**Comment by HenrikSantos** [comment]
As zsh is widely used, I think it's better to use the option you suggested previously, `<prop>`, or allow both syntaxes and explain this problem with zsh in the documentation.
